import ExcelJS from "exceljs";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ReportResult } from "./reports.service";

export class ExportService {
  /**
   * Export report data as standard CSV
   */
  static generateCSV(report: ReportResult, generatedBy: string = "Administrator"): string {
    const lines: string[] = [];

    // Header metadata
    lines.push(`"MANIFEST KAPCHORWA - MINISTRY MANAGEMENT SYSTEM"`);
    lines.push(`"Report Title: ${report.title}"`);
    lines.push(`"Generated At: ${new Date(report.generatedAt).toLocaleString("en-UG", { timeZone: "Africa/Kampala" })}"`);
    lines.push(`"Generated By: ${generatedBy}"`);
    if (report.dateRange?.from || report.dateRange?.to) {
      lines.push(`"Date Filter: ${report.dateRange.from || "Start"} to ${report.dateRange.to || "Present"}"`);
    }
    lines.push(""); // Empty line

    // Column Headers
    const escapedHeaders = report.headers.map((h) => `"${h.replace(/"/g, '""')}"`);
    lines.push(escapedHeaders.join(","));

    // Data rows
    for (const row of report.rows) {
      const rowValues = report.headers.map((h) => {
        const val = row[h];
        if (val === null || val === undefined) return `""`;
        return `"${String(val).replace(/"/g, '""')}"`;
      });
      lines.push(rowValues.join(","));
    }

    return lines.join("\r\n");
  }

  /**
   * Export report data as styled Excel (.xlsx) file using ExcelJS
   */
  static async generateExcel(report: ReportResult, generatedBy: string = "Administrator"): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = "Manifest Kapchorwa";
    workbook.created = new Date();

    const sheet = workbook.addWorksheet("Report", {
      views: [{ showGridLines: true }],
    });

    // Brand Title Header
    sheet.mergeCells("A1:G1");
    const titleCell = sheet.getCell("A1");
    titleCell.value = "MANIFEST KAPCHORWA - CHURCH MINISTRY SYSTEM";
    titleCell.font = { name: "Arial", size: 14, bold: true, color: { argb: "FFFFFFFF" } };
    titleCell.fill = {
      type: "pattern",
      pattern: "solid",
      fgColor: { argb: "FF274225" }, // Deep Forest Green
    };
    titleCell.alignment = { vertical: "middle", horizontal: "center" };
    sheet.getRow(1).height = 30;

    // Report Sub-Header
    sheet.mergeCells("A2:G2");
    const subCell = sheet.getCell("A2");
    subCell.value = `${report.title} | Generated: ${new Date(report.generatedAt).toLocaleString()} by ${generatedBy}`;
    subCell.font = { name: "Arial", size: 10, italic: true, color: { argb: "FF333333" } };
    subCell.alignment = { vertical: "middle", horizontal: "center" };
    sheet.getRow(2).height = 20;

    sheet.addRow([]); // Blank row at 3

    // Summary Section if present
    if (report.summary) {
      const summaryKeys = Object.keys(report.summary);
      const summaryRow = sheet.addRow(summaryKeys);
      summaryRow.font = { bold: true, size: 9, color: { argb: "FF7F3F2C" } }; // Clay
      const summaryValues = Object.values(report.summary);
      const valRow = sheet.addRow(summaryValues);
      valRow.font = { bold: true, size: 11 };
      sheet.addRow([]); // Blank row
    }

    // Table Header Row
    const headerRow = sheet.addRow(report.headers);
    headerRow.font = { name: "Arial", size: 11, bold: true, color: { argb: "FFFFFFFF" } };
    headerRow.eachCell((cell) => {
      cell.fill = {
        type: "pattern",
        pattern: "solid",
        fgColor: { argb: "FF3A5F37" }, // Highland Forest Green
      };
      cell.alignment = { vertical: "middle", horizontal: "center" };
      cell.border = {
        top: { style: "thin" },
        left: { style: "thin" },
        bottom: { style: "medium" },
        right: { style: "thin" },
      };
    });
    headerRow.height = 25;

    // Data Rows with alternating zebra stripes
    report.rows.forEach((rowData, idx) => {
      const rowVals = report.headers.map((h) => rowData[h] ?? "-");
      const row = sheet.addRow(rowVals);
      const isEven = idx % 2 === 0;

      row.eachCell((cell) => {
        cell.font = { name: "Arial", size: 10 };
        cell.border = {
          top: { style: "thin", color: { argb: "FFE0E0E0" } },
          left: { style: "thin", color: { argb: "FFE0E0E0" } },
          bottom: { style: "thin", color: { argb: "FFE0E0E0" } },
          right: { style: "thin", color: { argb: "FFE0E0E0" } },
        };
        if (!isEven) {
          cell.fill = {
            type: "pattern",
            pattern: "solid",
            fgColor: { argb: "FFF8F5ED" }, // Cream 100
          };
        }
      });
    });

    // Auto-fit column widths
    sheet.columns.forEach((column) => {
      let maxLen = 12;
      column.eachCell?.({ includeEmpty: true }, (cell) => {
        const valStr = cell.value ? cell.value.toString() : "";
        if (valStr.length > maxLen) {
          maxLen = Math.min(valStr.length + 3, 40);
        }
      });
      column.width = maxLen;
    });

    const arrayBuffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(arrayBuffer);
  }

  /**
   * Export report data as clean PDF document
   */
  static generatePDF(report: ReportResult, generatedBy: string = "Administrator"): Buffer {
    const doc = new jsPDF({
      orientation: report.headers.length > 6 ? "landscape" : "portrait",
      unit: "pt",
      format: "a4",
    });

    // Header Background
    doc.setFillColor(39, 66, 37); // Deep Highland Green
    doc.rect(0, 0, doc.internal.pageSize.width, 50, "F");

    // Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("MANIFEST KAPCHORWA", 40, 25);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text("Church Ministry Administration System — Kapchorwa, Uganda", 40, 40);

    // Report Title & Meta
    doc.setTextColor(40, 40, 40);
    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.text(report.title, 40, 75);

    doc.setFontSize(8.5);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    const dateStr = `Generated: ${new Date(report.generatedAt).toLocaleString()} by ${generatedBy}`;
    doc.text(dateStr, 40, 90);

    if (report.dateRange?.from || report.dateRange?.to) {
      doc.text(`Period: ${report.dateRange.from || "All"} to ${report.dateRange.to || "Present"}`, 40, 103);
    }

    // AutoTable for data
    const tableBody = report.rows.map((row) => report.headers.map((h) => String(row[h] ?? "-")));

    autoTable(doc, {
      startY: report.dateRange ? 115 : 105,
      head: [report.headers],
      body: tableBody,
      theme: "striped",
      headStyles: {
        fillColor: [58, 95, 55],
        textColor: 255,
        fontStyle: "bold",
        fontSize: 8.5,
      },
      bodyStyles: {
        fontSize: 8,
        textColor: 30,
      },
      alternateRowStyles: {
        fillColor: [248, 245, 237],
      },
      margin: { left: 40, right: 40 },
      didDrawPage: (data) => {
        // Footer page numbering
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${data.pageNumber} | Manifest Kapchorwa Confidential Report`,
          doc.internal.pageSize.width / 2,
          doc.internal.pageSize.height - 20,
          { align: "center" }
        );
      },
    });

    const pdfArrayBuffer = doc.output("arraybuffer");
    return Buffer.from(pdfArrayBuffer);
  }
}
